swagger: 2.0
openapi: 3.0.0
info:
  version: '1.0.0'
  title: ''
  description: ''
paths:
  /company:
    get:
      summary: Get company list
      responses:
        '200':
          description: '{company_id: company_name}'
  /company/{id}:
    get:
      summary: Get company name by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  company_id:
                    type: integer
                  company_name:
                    type: string
  /company/add:
    post:
      summary: Add new company
      parameters:
        - name: company
          in: body
          required: true
          schema:
            type: object
            required:
              - company_name
            properties:
              company_name:
                type: string
      responses:
        '200':
          description: Company was added successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  company_id:
                    type: integer
                  company_name:
                    type: string
  /employee:
    get:
      summary: Get employee list
      responses:
        '200':
          description: '{id: employee_id, name: employee_name}'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
  /employee/add:
    post:
      summary: Add new employee
      parameters:
      - name: new_employee
        in: body
        required: true
        schema:
          type: object
          required:
            - employee_name
          properties:
            employee_name:
              type: string
      responses:
        '200':
          description: Employee was added successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
  /employee/assign:
    put:
      summary: Assign employee to company
      parameters:
        - name: employee_to_company
          in: body
          required: true
          schema:
            type: object
            required:
              - employee_id
                company_id
            properties:
              employee_id:
                type: integer
              company_id:
                type: integer
      responses:
        '200':
          description: Employee was successfully assigned to company.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  comapny:
                    type: integer
                  phone:
                    type: string
  /company/goods/add:
    post:
      summary: Add new item
      parameters:
      - name: new_item
        in: body
        required: true
        schema:
          type: integer
          required:
            - item_name
              company_id
          properties:
            item_name:
              type: integer
            company_id:
              type: integer
      responses:
        '200':
          description: Item was added successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  company:
                    type: integer
  /company/goods/assign:
    put:
      summary: Assign item to employee
      parameters:
      - name: item_to_employee
        in: body
        required: true
        schema:
          type: object
          required:
          - item_id
            employee_id
          properties:
            item_id:
              type: integer
            employee_id:
              type: integer
      responses:
        '200':
          description: Item was successfully assigned to employee.
          content:
            application/json:
              schema:
                type: object
                properties:
                  item_id:
                    type: integer
                  employee_id:
                    type: integer